 version: '3.6'
 services:

  authservice:
    image: authservice
    container_name: authservice
    build:
      context: ./authservice
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    # depends_on:
    #   - db
    environment:
      - CONTAINER_NAME=authservice
      - PORT=7001
      # - DB_USER=${DB_USER:-postgres}
      # - DB_PASSWD=${DB_PASSWORD:-postgres}
      # - DB_URL=${DB_URL:-r2dbc:postgresql://db:5432/db}
    networks:
      - default

  apartowner:
    image: apartowner
    container_name: apartowner
    build:
      context: ./apartowner
      dockerfile: Dockerfile
    ports:
      - "7002:7002"
    environment:
      - CONTAINER_NAME=apartowner
      - PORT=7002
    networks:
      - default

# <-- 下記設定を参考にインデントに気をつけながらservicesの内容を書く -->
# <-- 6~11行目に関しては一旦考えなくて良い -->

# x-common: &common
#   working_dir: /go/src/microservice
#   tty: true
#   expose:
#       - 8080
#   command: bash -c "go run main.go"

# services:
#   nginx-proxy:
#     image: openjdk:17 
#     ports:
#       - "7000:7000"
#     tty: true  
#     volumes:
#       - ./server:/srv:cached
#     working_dir: /srv

# services:
#   nginx-proxy:
#     image: jwilder/nginx-proxy:alpine
#     ports:
#       - "80:80"
#     volumes:
#       - /var/run/docker.sock:/tmp/docker.sock:ro
#       - ./conf:/etc/nginx/vhost.d
#     depends_on:
#       - service-a
#       - service-b
#       - service-c

#   termination:
#     image: containous/whoami
#     environment:
#       - VIRTUAL_HOST=localhost

#   service-a:
#     <<: *common
#     build:
#       context: "./service-a"
#     volumes:
#       - ./service-a:/go/src/microservice

#   service-b:
#     <<: *common
#     build:
#       context: "./service-b"
#     volumes:
#       - ./service-b:/go/src/microservice

#   service-c:
#     <<: *common
#     build:
#       context: "./service-c"
#     volumes:
#       - ./service-c:/go/src/microservice
