version: '3'

# <-- インデントに気をつける -->

services:
  web-app:
    # ./web-appにindex.htmlを作るとコンテナ内の/usr/src/web-appにもindex.htmlが作られる
    # voluemsについての参考サイト https://www.nyamucoro.com/entry/2018/08/13/222617
    volumes:
      - .:/usr/src/
      - /usr/src/web-app/node_modules
    # Dockerfileの実行
    build:
      # contextをルートディレクトリにし、Dockerfileを参照させる
      context: .
      dockerfile: Dockerfile_web-app
    container_name: web-app
    # 実行させたいコマンド
    # command: sh -c 'cd web-app && yarn start'
    # コンテナを起動させ続けるか
    tty: true
    # コンテナ側とホスト側のポートの設定
    ports:
      - 3000:3000
      # storybook用のポート
      - 6006:6006
